function elong = parallelFunction( p_list, numReps,     ...
                                   finalTime, N, alpha, ... 
                                   rho, w, s, dt, g,    ...
                                   L, theta, pauseTime, ...
                                   isAnime, isPeriodic )


elong = zeros(numReps, length(p_list));
                               
for p_idx=1:length(p_list) % proportion
    p = p_list(p_idx);
    for r=1:numReps        % repetitions  
        elong(r, p_idx) = ...
                             simulation( finalTime, N, alpha, ... 
                                         rho, w, s, dt, g, p, ...
                                         L, theta, pauseTime, ...
                                         isAnime, isPeriodic );
%     % monitor inner progress
%     disp(['r: ',num2str(r),' p: ', num2str(p_idx)]);                      
    end                    % repetitions

end                        % proportion